# Simple makefile for the asynchronous I/O test program

PROG    = asynctest
SOURCES = asynctest.cxx

ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif

include $(PTLIBDIR)/make/ptlib.mak

# End of Makefile
