# Simple makefile for the JavaScript test program

PROG    = js_test
SOURCES = js_test.cxx

ifndef PTLIBDIR
PTLIBDIR=$(HOME)/ptlib
endif

include $(PTLIBDIR)/make/ptlib.mak

# End of Makefile
