
PLUGIN_NAME	= v4l2
PLUGIN_FAMILY	= device/videoinput
PLUGIN_LIBS	=
PLUGIN_SOURCES	= vidinput_v4l2.cxx vidinput_names.cxx

PLUGIN_CPPFLAGS = $(V4L2_CFLAGS)
PLUGIN_LIBS     = $(V4L2_LIBS)

include ../../make/plugins.mak
